# Generated by Django 4.0.6 on 2024-03-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationModel',
            new_name='Notification',
        ),
    ]
